/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stopwatch.gui;

import com.google.gson.Gson;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.List;
import javax.swing.JOptionPane;
import stopwatch.server.Request;
import stopwatch.server.Response;

/**
 *
 * @author olive
 */
public class Client extends javax.swing.JFrame {
    private MyConnectionWorker worker;
    
    
    public Client() {
        initComponents();
        setTitle("Stoppuhr");
        setMinimumSize(new Dimension(300, 350));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpanEast = new javax.swing.JPanel();
        jbutConnect = new javax.swing.JButton();
        jbutDisconnect = new javax.swing.JButton();
        jbutStart = new javax.swing.JButton();
        jbutStop = new javax.swing.JButton();
        jbutClear = new javax.swing.JButton();
        jbutEnd = new javax.swing.JButton();
        jpanCenter = new javax.swing.JPanel();
        jlabTimer = new javax.swing.JLabel();
        jpanNorth = new javax.swing.JPanel();
        jlabRefreshrate = new javax.swing.JLabel();
        jslideRate = new javax.swing.JSlider();
        jlab1ms = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpanEast.setMinimumSize(new java.awt.Dimension(110, 163));
        jpanEast.setPreferredSize(new java.awt.Dimension(110, 163));
        jpanEast.setLayout(new java.awt.GridLayout(6, 1, 5, 5));

        jbutConnect.setText("Connect");
        jbutConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutConnectActionPerformed(evt);
            }
        });
        jpanEast.add(jbutConnect);

        jbutDisconnect.setText("Disconnect");
        jbutDisconnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutDisconnectActionPerformed(evt);
            }
        });
        jpanEast.add(jbutDisconnect);

        jbutStart.setText("Start");
        jbutStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutStartActionPerformed(evt);
            }
        });
        jpanEast.add(jbutStart);

        jbutStop.setText("Stop");
        jbutStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutStopActionPerformed(evt);
            }
        });
        jpanEast.add(jbutStop);

        jbutClear.setText("Clear");
        jbutClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutClearActionPerformed(evt);
            }
        });
        jpanEast.add(jbutClear);

        jbutEnd.setText("End");
        jbutEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutEndActionPerformed(evt);
            }
        });
        jpanEast.add(jbutEnd);

        getContentPane().add(jpanEast, java.awt.BorderLayout.EAST);

        jpanCenter.setLayout(new java.awt.GridBagLayout());

        jlabTimer.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jlabTimer.setText("0.000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        jpanCenter.add(jlabTimer, gridBagConstraints);

        getContentPane().add(jpanCenter, java.awt.BorderLayout.CENTER);

        jlabRefreshrate.setText("Refreshrate: 1s");
        jpanNorth.add(jlabRefreshrate);

        jslideRate.setPreferredSize(new java.awt.Dimension(500, 26));
        jpanNorth.add(jslideRate);

        jlab1ms.setText("1ms");
        jpanNorth.add(jlab1ms);

        getContentPane().add(jpanNorth, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutStopActionPerformed
        worker.setTryToStop(true);
    }//GEN-LAST:event_jbutStopActionPerformed

    private void jbutStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutStartActionPerformed
        worker.setTryToStart(true);
    }//GEN-LAST:event_jbutStartActionPerformed

    private void jbutDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutDisconnectActionPerformed
        worker.setCancel(true);
        jbutConnect.setEnabled(true);
        jbutDisconnect.setEnabled(false);
        jbutStart.setEnabled(false);
        jbutStop.setEnabled(false);
        jbutClear.setEnabled(false);
        jbutEnd.setEnabled(false);
    }//GEN-LAST:event_jbutDisconnectActionPerformed

    private void jbutConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutConnectActionPerformed
        try {
            worker = new MyConnectionWorker("127.0.0.1", 8080);
            worker.execute();
            jbutConnect.setEnabled(false);
            jbutDisconnect.setEnabled(true);
            jbutEnd.setEnabled(true);
        } catch(Exception ex) {
            JOptionPane.showMessageDialog(this, "Konnte nicht mit dem Server verbinden", "Fehler", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_jbutConnectActionPerformed

    private void jbutClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutClearActionPerformed
        worker.setTryToClear(true);
    }//GEN-LAST:event_jbutClearActionPerformed

    private void jbutEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutEndActionPerformed
        worker.setTryToEnd(true);
    }//GEN-LAST:event_jbutEndActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutClear;
    private javax.swing.JButton jbutConnect;
    private javax.swing.JButton jbutDisconnect;
    private javax.swing.JButton jbutEnd;
    private javax.swing.JButton jbutStart;
    private javax.swing.JButton jbutStop;
    private javax.swing.JLabel jlab1ms;
    private javax.swing.JLabel jlabRefreshrate;
    private javax.swing.JLabel jlabTimer;
    private javax.swing.JPanel jpanCenter;
    private javax.swing.JPanel jpanEast;
    private javax.swing.JPanel jpanNorth;
    private javax.swing.JSlider jslideRate;
    // End of variables declaration//GEN-END:variables

    
    private class MyConnectionWorker extends ConnectionWorker {

        public MyConnectionWorker(String host, int port) throws IOException {
            super(host, port);
        }

        @Override
        protected void process(List<Response> list) {
            for(Response r : list) {
                if(r.isMaster()) {
                    jbutConnect.setEnabled(false);
                    jbutDisconnect.setEnabled(true);
                    jbutStart.setEnabled(true);
                    jbutStop.setEnabled(true);
                    jbutClear.setEnabled(true);
                    jbutEnd.setEnabled(true);
                } else {
                    jbutConnect.setEnabled(false);
                    jbutDisconnect.setEnabled(true);
                    jbutStart.setEnabled(false);
                    jbutStop.setEnabled(false);
                    jbutClear.setEnabled(false);
                    jbutEnd.setEnabled(false);
                }  
                
                if(r.isRunning()) {
                    jbutStart.setEnabled(false);
                    jbutStop.setEnabled(true);
                    jbutClear.setEnabled(true);
                } else {
                    jbutStart.setEnabled(true);
                    jbutStop.setEnabled(false);
                    jbutClear.setEnabled(false);                    
                }
                jlabTimer.setText(String.format("%.3f", r.getTime()));
            }
        }
        
        @Override
        protected void done() {
            try {
                get();
            } catch(Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(Client.this, "Unbekannter Fehler", "Fehler", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
}
